name: AMBwatches
favicon: null
layout_spectrum: 0.0061263409443199635
typography_spectrum: 0.3222257618326694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6255612580571324
  lightness: 0.742820052197203
  saturation: 0.0924705162178725
  rhythmicContrast: 0.4071267391555011
purpose: []
